language: erlang

env:
  global:
    - LUAROCKS_BASE=luarocks-2.0.13
  matrix:
    - "LUA=lua5.1 LUA_DEV=liblua5.1-dev     LUA_VER=5.1 LUA_SFX=5.1    LUA_LIB=lua5.1"
    - "LUA=lua5.2 LUA_DEV=liblua5.2-dev     LUA_VER=5.2 LUA_SFX=5.2    LUA_LIB=lua5.2"

branches:
  only:
    - master

before_install:
  - "sudo apt-get install $LUA"
  - "sudo apt-get install $LUA_DEV"

  # Install a recent luarocks release.
  - wget http://luarocks.org/releases/$LUAROCKS_BASE.tar.gz
  - tar zxvpf $LUAROCKS_BASE.tar.gz
  - cd $LUAROCKS_BASE
  - ./configure
    --lua-version=$LUA_VER --lua-suffix=$LUA_SFX 
  - sudo make 
  - sudo make install
  - cd $TRAVIS_BUILD_DIR

install:
  - sudo luarocks install https://raw.github.com/moteus/luasocket/unstable/rockspecs/luasocket-2.0.2.mot-1.rockspec
  - sudo luarocks install lunitx
  - sudo luarocks install lpeg 0.10 || sudo luarocks install lpeg || echo 'skip'
  - sudo luarocks install https://raw.github.com/moteus/luacrypto/master/rockspecs/luacrypto-git-1.rockspec
  - sudo luarocks install lua-iconv
  - sudo luarocks make rockspecs/pop3-scm-0.rockspec

script: "cd test && lunit.sh test-message.lua"

notifications:
  email:
    on_success: change
    on_failure: always
