language: erlang

env:
  - LUA="lua5.1"

branches:
  only:
    - master

install:
  - sudo apt-get install luarocks
  - sudo luarocks install luasocket
  - sudo luarocks install lunitx
  - sudo luarocks install lpeg
  - sudo luarocks install luacrypto
  - sudo luarocks install lua-iconv
  - sudo luarocks make rockspecs/pop3-scm-0.rockspec

script: "cd test && lunit.sh test-message.lua"

notifications:
  recipients:
    - mimir@newmail.ru
  email:
    on_success: change
    on_failure: always
